[package]
name = "minigrep_io_practice"
version = "0.1.0"
edition = "2021"
description = "An I/O Project: Building a Command Line Program"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1


[dependencies]
